### ISSUE TITLE
Add more data.

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [jhagas/wetonizer-app#1]
As per this website - https://www.walisongo.co.id/cek-weton/

**Comment by jhagas** [comment]
Thanks for your feedback,
i think my site offers more data than your reference. The calculation from gregorian to hijri calendar turns out to be different than to javanese calendar. Your reference site just assuming the same calculation for hijri and javanese calendar..

For more information
https://drive.google.com/file/d/1W8x-RD0grGrWVTlbcFt3O81fkL63IgZG/view
In above link, there is some difference, let's say in April 22nd 2023. 1 Pon is for javanese calendar, and in above is a arabic number of 2, clearly there is some difference in that
<img width="837" alt="image" src="https://github.com/jhagas/wetonizer-app/assets/76400782/a26180a7-9cae-4fbf-b464-bca0ee683a7e">

I will add some information for matching partners, etc with neptu numbers later..

**Comment by rahulkumarsingh73690** [comment]
Thanks @jhagas 

Please launch the npm package if possible
